### ISSUE TITLE
Responsiveness in Header

### ISSUE THREAD

**Issue by amanpasricha** [amanpasricha/Hotel-Booking#1]
The header of the project is breaking down below 1200 pixels in width. Responsiveness needs to be fixed in header.php and styling is in css/style.css

**Comment by amanj752** [comment]
I will do it assigned to me

**Comment by amanpasricha** [comment]
> I will do it assigned to me

Sure. Thank you for taking out some time for this.

**Comment by amanj752** [comment]
add hactoberfest label in this issue after that it will be count
